name=NeuNVS
version=2.0.1
author=Ulywae <ulywae@gmail.com>
maintainer=Ulywae <ulywae@gmail.com>
sentence=Ultra-fast and secure NVS library for ESP32 with Intelligent Hardware Protection.
paragraph=NeuNVS is an ID-based storage engine featuring CRC16 integrity, smart auto-commit, and exclusive Thermal Lockdown mode. It includes active wear-leveling (Migration) to protect Flash memory from burn-out and abuse.
category=Data Storage
url=https://github.com/ulywae/NeuNVS
architectures=esp32
includes=NeuNVS.h
