name=NeuNVS
version=1.3.0
author=Ulywae <ulywae@gmail.com>
maintainer=Ulywae <ulywae@gmail.com>
sentence=Ultra-fast and secure NVS wrapper for ESP32 with hardware protection.
paragraph=NeuNVS is an ID-based storage library that is 6x faster than Preferences. It features XOR data integrity, Dirty Check efficiency, and an exclusive Lockdown mode to protect Flash memory from abuse.
category=Data Storage
url=https://github.com/ulywae/NeuNVS
architectures=esp32
